"""device

Revision ID: 9cc5ce46bd47
Revises: 8fcc0de9e00a
Create Date: 2025-04-25 10:01:51.470536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc5ce46bd47'
down_revision: Union[str, None] = '8fcc0de9e00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('devices', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
